# host: 172.25.205.43
# host: 172.25.192.1
host: 127.0.0.1
# host: 192.168.61.1
# host: 192.168.70.81
port: 8000

public_key: |
  -----BEGIN PUBLIC KEY-----
  MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEArZ03/NhByIM5+jBp3SIN
  wCNFGTzV0tdo4gSRR9ygA2e4/Q08Xq9f0B0s3rEx6W/RSbHySY1xEDLXKm9woBjV
  4uvy5LnzHtwj1WxzOITyaYiReudM59Shrd2XhwKS0sKAJrZg9D7l3M/OJTHWc0yS
  AthNrcpEdmRdJGI8IhJ1exkG9mqHH7zboZ3fFoRjyS7U94SCIPIpNdqVboLIU+EK
  htaNwPgV5+zSxSlrifcdGqHf4mFgRsWWpnKapiIIPg62C1Crs3Aob8/se4a2tHRH
  bslirEKFOjJ4HaeBmR4yuRVr2oy6Z/uOLgbZl/W/423/MlPuh8kdCwxVRWX1LlcE
  3kzztx9QkJm3/b99FvHQfVgSBIz3QSPpszJtFNQEVT+e914RxK4S/ZcfGkSKJa65
  FmHSmRKUATWu93h3YZhLOARu6o7wCQpRmNylSfmgtkVWdXsPNhSfddHzEFQg4ZjG
  jAjOw2qoyEYYin6Ja27e/dwalK2cO3AkkzG7jwOf8oDSxqgYeRD2j81jcXMmS0RX
  WO9JTMHu1N3m5eeYOUXRvHYD46qj+S5hboi51uCWdjch5fzgoAUjpnBd8mzUg/OR
  7gjn7/UTu3FXpdfIQXBLmd1sbm5TxyUN8zZ5LUG2wz6ngncG3EZAaYhJuctYSmBH
  dDY8Kd9Cdgl1M5weV16LlQkCAwEAAQ==
  -----END PUBLIC KEY-----
