# host: 172.25.205.43
# host: 172.25.192.1
host: 127.0.0.1
# host: 192.168.61.1
# host: 192.168.70.81
port: 8000

private_key: |
  -----BEGIN PRIVATE KEY-----
  MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQCtnTf82EHIgzn6
  MGndIg3AI0UZPNXS12jiBJFH3KADZ7j9DTxer1/QHSzesTHpb9FJsfJJjXEQMtcq
  b3CgGNXi6/LkufMe3CPVbHM4hPJpiJF650zn1KGt3ZeHApLSwoAmtmD0PuXcz84l
  MdZzTJIC2E2tykR2ZF0kYjwiEnV7GQb2aocfvNuhnd8WhGPJLtT3hIIg8ik12pVu
  gshT4QqG1o3A+BXn7NLFKWuJ9x0aod/iYWBGxZamcpqmIgg+DrYLUKuzcChvz+x7
  hra0dEduyWKsQoU6Mngdp4GZHjK5FWvajLpn+44uBtmX9b/jbf8yU+6HyR0LDFVF
  ZfUuVwTeTPO3H1CQmbf9v30W8dB9WBIEjPdBI+mzMm0U1ARVP573XhHErhL9lx8a
  RIolrrkWYdKZEpQBNa73eHdhmEs4BG7qjvAJClGY3KVJ+aC2RVZ1ew82FJ910fMQ
  VCDhmMaMCM7DaqjIRhiKfolrbt793BqUrZw7cCSTMbuPA5/ygNLGqBh5EPaPzWNx
  cyZLRFdY70lMwe7U3ebl55g5RdG8dgPjqqP5LmFuiLnW4JZ2NyHl/OCgBSOmcF3y
  bNSD85HuCOfv9RO7cVel18hBcEuZ3WxublPHJQ3zNnktQbbDPqeCdwbcRkBpiEm5
  y1hKYEd0Njwp30J2CXUznB5XXouVCQIDAQABAoICAEkFEwM5QZG//6aGrj/fjsD9
  FJbky1n+V5KYMTJ0TKih+2ATLQz13ep+Gt0e0ctIyFGikjD1WFRjzbN/Y3MyfuMO
  Mf6ZZvPXywp8rolbAUn5spZqqiHngIjL5mtWXcJfI98kXerceXlBvYZPS876qX6g
  0ysBI4JX/ATNfFUoRlkb0Z3aeDKVEBsNd0LVM9Lt64yfIswQjdykrqzoPLFquS61
  FrHOpggBxzQ9k4lXcdo9sxhXtFKP0Cj5kqnFLopLTa28pDq4NYmxfdkGc9m5/kFO
  Wj3xTG+JwpNWXF+2H8dQhyhIgC4z0zzwjJwpNCfHn8nfGzfpEloPOd4SX+i5mMXl
  VQKCSavIHXf8Ng7TB2VlEuFvLnkz6JK7KJC8NvQh9pK/xAoOTeiPtO0Ou0ZhGh1N
  UvXDRz8llAkiEIY9VBRYKjy2dLJfDMjLUMzyefnNmZp/66fuVtovsHhdEUveMGA7
  ymqtRAbDPC4BUEsz89li3X4vlzJ8UvKAASPPcA+DyuALhfXQePOoegT41MJYxOlb
  1SsUWHHzpFynxFqRZECVwwNMfbllf8EiJ97OOxo82CMQkbLD0+CzdgDnD7pW54sG
  jM/pQkTlBU/Zq2SL6OrTNAUGYypIF7EyCzD/Fc34qAXNnMvIRcJwwlfM5LHA1dxa
  8bFtnZ5KeoDtesseHm9xAoIBAQDZJGtcdUcrV9uJvfn/ZQ0etPCoIJhgxg7p8Fzh
  6yzh8akzUXy7/J25gLAP594lZ8Lyi2WYu0oas+GhtTVPBRKrts2SWizHrMQ7TjbC
  iw6NLxWVSwqXjQWpgUKpbKBJO9MoFrJDVPwxmadgN96mBXE1bGMpiiPyYP0SXF54
  ETgv8xF2lHqXo84DTRArTCxEWjOcSwPvHmdwSjx8PwXqn97tOcd3dJRO3xS/u8oP
  Y20sjiHAtPT7ro33ujG2y/8b60GW4FQrxIyMioN2UUSjUCML1hKJrKljcOz0p2pD
  nap5lrRo4sUBWWZJCZv+XdMhNWVP6WgbesaD/xB5S2NV3I0vAoIBAQDMrreKIIPZ
  8zWMqIjuf5HXIv02mzc/Rxhqj2fq5OJw+ERpeK0ex3EDknuOyyvRrl0114l1C3oF
  9igF2WOMTtxOvTHSQjDtZIaKStmtOzYLaYmjziCfTGMYQnlSfq0f4FSIzDdrxP4g
  ulDFZcEzZ4+ikTTscvWdcIe31qDYDOYK7399UedOkz99zZcClqoctm4FB4H7rvig
  yHVyBqtCicfk9k8GjwAXtNAgghvq7TBrs8DijtPQONVieSNyFIrflWsKyqjrDu5V
  dNuoIYWq3XVxar4rYmt7FaNilP5MwWnFWCWjuDHSR9ZYul8eCO4AGuOJzQ0JcehJ
  FeMp/x5zXSNHAoIBAB32Q4YvfJGDfvyDpUJTXDsXdnmMfdokmhw3mWlm/Pt0UAeP
  v+lkkxLsqd6X/PQmXCUBjRRFC5WhqomYqnFr3sao47bFEJbAxRb11OKFM43RqGXA
  RAbjY5ufBWbBYWCZi6plb1WRHXdun0TMkMFR0OwxN4Gc2RbxwRnOew6QObOME6XM
  GRphdOTJtmhzC0ynMaXoR/Ovu1AoPi5at+NHCgirx1U5VdmIOKG4NMpoysCyIAAq
  N/+ed2JuY7u4bEwa6yL5c0PSzB38YuVpk1IBlcRlVot+sqTRCTE9BJGt6L78R4qN
  d+eWwWFknQy9P4u+hWtAZqgcCdZe1JQYDe3kD+sCggEAdXCuKNfdL1nH2Ov+nXGe
  2WTfCszmVy1Qyht8UZ+AebdJcYbnNijTJGyQ7m6OtuGn47PGz9yE6BTEBA8meiPp
  blhJ1M1by2oJdCHcYfP+X2/vpIgp2Zz3orzJZdb/OLH7bv5VskU2Vsrwe0KWJwt9
  s5ZDWoPff7VIeefxI+XKvG2MpfgvkrsUC/fBdJ/D/XODDumu4B0V1RMPqBxBeY0a
  n7nfv/Ce6fs6C9z7bcEoLjPWMWgoCmoBrV26Q8ObpwvRfkCnyS8o+ulw+zg4vMAS
  mb/YW4Y+C0JwG6lHe/zh1nRsLFMMaw4C46gT2WTgQjkrYy6/EzNDR2QCkl8qNqEz
  EwKCAQEAmr095scapYvAtJza1UYs/OMfWB/xlQqx5YmoKOrejBPxopPG5ZQo238J
  In8qvIamHCBl10YmGKQW7+76RVEg0rCpEYjkRJun8PqvAQZCrJGwBNjhmQBPKH/Y
  V13CpqtQqn5peZOYOTjvVZ3mN9XMYOVplCNP4eJ6+lQsFvUy1slpRKP+z7ZQjgUn
  l0TGsuy/cJwv8QPX5lJvJEgE1Iw78Vmvwt1ioBhENGUv2YIyTcP1ARog8wxjNakv
  asDz96JaLgKhHsAREaudwmLxaXwdMQwp9NznHFaqupFsY8ysde+UBoukCDOhn71z
  vJcaNm/HKzOkIXt3eDLZGuZosVGUhQ==
  -----END PRIVATE KEY-----